[package]
name = "toy-payments-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.62"
clap = { version = "3.2.17", features = ["derive"] }
csv = "1.1.6"
serde = { version = "1.0.144", features = ["derive"] }
